### ISSUE TITLE
Log filter: filtrare gli eventi di un log

### ISSUE THREAD

**Issue by mining4UML** [mining4UML/UMLMiner#67]
Creare una GUI che permetta di:
1. visualizzare tutte le attività riportando per ognuna di esse nome, numero di istanze e frequenza;
2. selezionare le attività per indicare quali tenere (retain) oppure quali rimuovere) remove
3. creare un nuovo log in base alle scelte operate nel punto 2.
Un esempio di GUI che si potrebbe creare è quello di seguito mostrato:
<img width="1338" alt="Screenshot 2023-07-05 alle 08 54 14" src="https://github.com/mining4UML/mining4UML/assets/129510707/59c189dc-3162-4a0c-8fa0-739d4dd324c4">

Converrebbe realizzare questa GUI in _RuM 4 UML Miner_ sfruttando così appieno le funzionalità di JavaFX.
Potrebbe essere la terza voce di menù nel menù laterale sinistro:
- Discovery
- Conformance Checking
- Log Filtering

**Comment by ardimento** [comment]
Nella versione RuM 0.7.0 è stata realizzata la funzione di Log filtering. Per cui non è più necessario sviluppare tale funzionalità in UML Miner ma, piuttosto, è necessario integrarla. Vedi issue #70
