### ISSUE TITLE
RuM 4 UML Miner: aggiunta di dati di dettaglio nel conformance report (log delle violazioni rilevate)

### ISSUE THREAD

**Issue by ardimento** [mining4UML/UMLMiner#68]
**Problema**
Al momento nel file delle violazioni generato da RuM si hanno record come, ad esempio, quello riportato di seguito
_[](absence2: [AssociationClass added to ClassDiagram][][][])_
con un numero di _violations_ uguale a _2_

Per poter fornire un feedback sulla violazione rilevata è necessario che per ogni **singola violazione** siano presenti le seguenti informazioni:
- nome e tipo del diagramma coinvolto;
- nome e tipo dell'elemento UML coinvolto (se presenti)
- nome e valore della proprietà coinvolti (se presenti)

_Solo così sarebbe possibile avere le informazioni di contesto utili alla _query string_ ottenuta dalla trasformazione della violazione rilevata._

Queste informazioni sono attualmente disponibili solo in formato grafico quando in _RuM 4 UML Miner_ nella _Conformance Checking_ si seleziona la voce _Sort Group By Violations_ e, dopo, si clicca dapprima su una violazione e poi su _Show Payloads_

**Comment by ardimento** [comment]
Grazie alle modifiche nella versione apportate nella versione 0.7.2 di RuM il report delle violazioni riporta le seguenti informazioni
![image_2023_11_08T15_19_21_127Z](https://github.com/mining4UML/UMLMiner/assets/22344643/387b2a6b-f1bc-4adc-9659-155f3d916eee)

Dopo ho personalizzato il codice di RuM in modo che nel report delle violazioni fossero presenti anche:

- nome e tipo del diagramma coinvolto;
- nome e tipo dell'elemento UML coinvolto (se presenti)
- nome e valore della proprietà coinvolti (se presenti)
Un esempio è riportato nell'immagine sottostante
<img width="1407" alt="Screenshot 2023-11-08 alle 22 19 18" src="https://github.com/mining4UML/UMLMiner/assets/22344643/d6ce2f52-3329-4270-8385-0b55c152d013">

**Comment by mining4UML** [comment]
Solved and committed to RuM fork.
