### ISSUE TITLE
RuM 4 UML Miner: aggiornamento alla versione 0.7.2 di RuM

### ISSUE THREAD

**Issue by ardimento** [mining4UML/UMLMiner#69]
Aggiornare la versione di RuM 4 UML Miner alla versione 0.7.2 di RuM (rilasciata in data 08 novembre 2023)
Sarebbe opportuno documentare tutto quanto è necessario per passare da una versione ad un'altra.

**Comment by mining4UML** [comment]
Updated to RuM version 0.7.3
