### ISSUE TITLE
Denied folder access

### ISSUE THREAD

**Issue by Peppo10** [mining4UML/UMLMiner#73]
Scenario esecuzione:
1. creazione progetto
2. aggiunta modello
3. aggiunta diagramma delle classi
4. aggiunta classi esempio e connettori
5. salvataggio
6. Export Logs Action

Nel log è presente:
`
[2023/11/24 11:29:04] [message] java.nio.file.AccessDeniedException: C:\Program Files\Visual Paradigm CE 17.1\bin\logs
`

```
[2023/11/24 11:33:02] [message] java.lang.NullPointerException
[2023/11/24 11:33:02] [message] at com.uniba.mining.logging.LogStreamer.countLogs(LogStreamer.java:137)
```

`Cannot write to folder: C:\Program Files\Visual Paradigm CE 17.1 (Access is denied)
`

OS: Windows 11 10.0 running on amd64
VP: Visual Paradigm Community Edition 17.1
JVM: 11.0.16.1

[File vp.log](https://github.com/mining4UML/UMLMiner/files/13459467/vp.log)

**Comment by mining4UML** [comment]
@Peppo10 , please re-run the scenario and deliberately trigger an exception. To do this, delete the "logs" folder located at _C:\Program Files\Visual Paradigm CE 17.1\bin_. Subsequently, create a project, generate a diagram, save the project, and utilize the "export logs" functionality.

If you encounter an exception, close Visual Paradigm. Right-click on the Visual Paradigm shortcut and select "Run as administrator." Repeat the scenario. Does the issue persist?

**Comment by Peppo10** [comment]
Ther is no logs folder in _C:\Program Files\Visual Paradigm CE 17.1\bin_ just because only TrustedInstaller has permission on it and "not elevated" program cannot access it.

Obviously if i run as administrator i can reach the folder and everythings works correctly.

So in this case **every windows user should run VP as administrator**?

**Comment by mining4UML** [comment]
> Obviously if i run as administrator i can reach the folder and everythings works correctly.
The focus is on the creation of the folder not the content reading. **Does the process successfully create these folders when they do not exist and VP is running as administrator?** 
>So in this case every windows user should run VP as administrator?
Definitely yes for the current version.

**Comment by Peppo10** [comment]
Does the process successfully create these folders when they do not exist and VP is running as administrator?

Yes, the plugin re-generate all the folders.

**Comment by Peppo10** [comment]
Does the process successfully create these folders when they do not exist and VP is running as administrator?

Yes, the plugin re-generate all the folders.
